# SPDX-FileCopyrightText: 2022 Shinoda Eiji, <syuilotan@yahoo.co.jp>, et al.
#
# SPDX-License-Identifier: AGPL-3.0-only

'⚙️Server':
- packages/backend/**/*

'🖥️Client':
- packages/client/**/*

'🧪Test':
- cypress/**/*
- packages/backend/test/**/*

'‼️ wrong locales':
- any: ['locales/*.yml', '!locales/ja-JP.yml']
