# SPDX-FileCopyrightText: 2022 Shinoda Eiji, <syuilotan@yahoo.co.jp>, et al.
#
# SPDX-License-Identifier: AGPL-3.0-only

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "misskey.fullname" . }}-configuration
data:
  default.yml: |-
    {{ .Files.Get "files/default.yml"|nindent 4 }}
    url: {{ .Values.url }}
