# SPDX-FileCopyrightText: 2022 Shinoda Eiji, <syuilotan@yahoo.co.jp>, et al.
#
# SPDX-License-Identifier: AGPL-3.0-only

apiVersion: v1
kind: Service
metadata:
  name: {{ include "misskey.fullname" . }}
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
      name: http
  selector:
		{{- include "misskey.selectorLabels" . | nindent 4 }}
