# SPDX-FileCopyrightText: 2022 Shinoda Eiji, <syuilotan@yahoo.co.jp>, et al.
#
# SPDX-License-Identifier: AGPL-3.0-only

contact_links:
  - name: 👪 Misskey Forum
    url: https://forum.misskey.io/
    about: Ask questions and share knowledge
  - name: 💬 Misskey official Discord
    url: https://discord.gg/Wp8gVStHW3
    about: Chat freely about Misskey
