# SPDX-FileCopyrightText: 2022 Shinoda Eiji, <syuilotan@yahoo.co.jp>, et al.
#
# SPDX-License-Identifier: AGPL-3.0-only

url: 'http://misskey.local'

# ローカルでテストするときにポートを被らないようにするためデフォルトのものとは変える(以下同じ)
port: 61812

db:
  host: localhost
  port: 54312
  db: test-misskey
  user: postgres
  pass: ''
redis:
  host: localhost
  port: 56312
id: aid
