# SPDX-FileCopyrightText: 2022 Shinoda Eiji, <syuilotan@yahoo.co.jp>, et al.
#
# SPDX-License-Identifier: AGPL-3.0-only

name: "Pull Request Labeler"
on:
  pull_request_target:
    branches-ignore:
      - 'l10n_develop'

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
