# SPDX-FileCopyrightText: 2022 Shinoda Eiji, <syuilotan@yahoo.co.jp>, et al.
#
# SPDX-License-Identifier: AGPL-3.0-only

name: Lint

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'yarn'
        cache-dependency-path: |
          packages/backend/yarn.lock
    - run: yarn install
    - run: yarn --cwd ./packages/backend lint

  client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'yarn'
        cache-dependency-path: |
          packages/client/yarn.lock
    - run: yarn install
    - run: yarn --cwd ./packages/client lint
